// Code generated by mockery v2.26.1. DO NOT EDIT.

package unitsoldmocks

import (
	context "context"

	"github.com/jmontesinos91/collector/internal/repositories/unitsold"
	mock "github.com/stretchr/testify/mock"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, unitID
func (_m *IRepository) FindByID(ctx context.Context, unitID int) (*unitsold.UnitsModel, error) {
	ret := _m.Called(ctx, unitID)

	var r0 *unitsold.UnitsModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*unitsold.UnitsModel, error)); ok {
		return rf(ctx, unitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *unitsold.UnitsModel); ok {
		r0 = rf(ctx, unitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unitsold.UnitsModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, unitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRouterID provides a mock function with given fields: ctx, routerID
func (_m *IRepository) FindByRouterID(ctx context.Context, routerID int) (*unitsold.UnitsModel, error) {
	ret := _m.Called(ctx, routerID)

	var r0 *unitsold.UnitsModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*unitsold.UnitsModel, error)); ok {
		return rf(ctx, routerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *unitsold.UnitsModel); ok {
		r0 = rf(ctx, routerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unitsold.UnitsModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, routerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRepository(t mockConstructorTestingTNewIRepository) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
