server:
  port: 8081

keys:
  public: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lUQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnNEFNSUlDQ1FLQ0FnQjdHV0IxOFhydWd5cWErQW1HMng4RCBnRXJJUnJxYWpvcG5kQ1diM0V4OGo5TjRpTFJwSFFVN1hPMEdWQzA4YlZZV2R2WE9qNHpzMWhodGRXNGRRQllWIG5CYTNWSEVNUGNQakx4V2dEWDRKWFpiYk52MjAxSXdJSHJKaGZheUM0cUE1dWI1ZHV3NCthaStvWmpKR1B1NjIgUGZGV3RwbmFCdUtCRnRHUG5pdjRXTXR6b0JRNUhBS29RQzJmL0tYTFNidllpeG9FT2liTWFQSXJyUW1lUXJ5WCAzZUs4MFJIVFRqU0pmN21qSHZRU2ZuNTBCNVVLem1kR2pZMnRwcmV1SU9oNlJXdzF4Z3QvMm0xaDArSURadlBEIDZRaEgrYnJyY1ZObFpHcjlzOGNNSkhQOGpod2ZvTGFYbEVvbHp6T2k1bWIxU0RvZ3Y0TWgrVm1OU3dpVTRLYlEgZ3lEY1NaSEJDT2E2bGsyM3VhcGFQTmovWFBtVTNNR1Y5LzZ4WlVRUWpvbS80cUdvRytwWnlNT0gxUVgzblk1UyBPRTV4cmdoS0RjbW4wMVZsajBUN0ljRStMaHZaZi9Bdko2TlJOa2FsU25WUUtJRHhJL1NzQVE2cFZvVW5jY2pSIEJvdUY1U2lIb2VVZ1QyMFRhVjJoM0o2aCt6aDBWVEhodEZ2Uk80OXdpeWJXMTRkV0h3LzE5T0F1S0s4TlhZTnQgSVdoTy9UVUNCaHo3WGxTeVVuY0I2OFpkV3hhN216ak92U0k3MWpvK1VnMGMzMnB2dm9TYTlEaG9HdGt6Nm9SQyBkcWFDMVA5NEViaDFKbS9iWGtnYm5lMVNFN3dqUUdnV2xOVFh2S1Z2eHRIeUsxS2V3VE9HbFBpZlloN3EvcFhWIGMyc1lMYVNMTWtoM0NqVTVEUS9NcFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"

database:
  dsn: "postgres://admin:omniview123@localhost:5432/collector2"
  pool: 80

olddatabase:
  dsn: "test:12345@tcp(10.26.24.9:3306)/sbo"
  pool: 10

omniview:
  server: "https://staging.api.omniview.cloud"
  timeout-in-seconds: 10
  max-retries: 3
  retry-wait-min-in-seconds: 2
  retry-wait-max-in-seconds: 90

service:
  name: go-collector2

kafka:
  secured-mode: false
  servers: "172.31.3.165:9092"
  user: ""
  pass: ""
  client-name: "collector2"